-- Idempotent schema bootstrap. Runs on startup against DATABASE_URL.
CREATE TABLE IF NOT EXISTS api_keys (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(255),
  api_key     varchar(255) NOT NULL UNIQUE,
  expires_at  timestamptz,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reminder (
  name varchar(20) PRIMARY KEY,
  note jsonb NOT NULL DEFAULT '{}'
);

CREATE SCHEMA IF NOT EXISTS stash;

CREATE TABLE IF NOT EXISTS stash.cinema_showing (
  s_bind    varchar(200),
  s_display text NOT NULL,
  s_name_en text NOT NULL,
  s_name_th text NOT NULL,
  s_url     text NOT NULL,
  n_time    integer NOT NULL DEFAULT 0,
  n_week    integer NOT NULL,
  n_year    integer NOT NULL,
  o_theater jsonb NOT NULL DEFAULT '[]',
  s_cover   text NOT NULL,
  s_genre   varchar(40) NOT NULL,
  t_release timestamptz NOT NULL,
  CONSTRAINT uq_cinema_name UNIQUE (s_bind, n_week, n_year)
);

CREATE TABLE IF NOT EXISTS stash.gold (
  tin        numeric DEFAULT 0,
  tin_ico    varchar(4),
  tout       numeric DEFAULT 0,
  tout_ico   varchar(4),
  usd_buy    numeric DEFAULT 0,
  usd_sale   numeric DEFAULT 0,
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS uq_updated_at ON stash.gold (updated_at);

CREATE TABLE IF NOT EXISTS stash.lottery (
  draw        date PRIMARY KEY,
  first_prize varchar(6) NOT NULL,
  front_three varchar(3)[],
  back_three  varchar(3)[],
  back_two    varchar(2)[],
  created_at  timestamptz DEFAULT now()
);
